
# THIS FILE IS AUTOGENERATED BY repo_build
import sys
import os
p = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if hasattr(os, "add_dll_directory"):
    add_library_path = os.add_dll_directory
else:
    def add_library_path(p):
        os.environ["PATH"] += os.pathsep + p                    
if os.path.exists(f"" + os.getenv("PYTHONPATH", default="") + ""):
    sys.path.append(f"" + os.getenv("PYTHONPATH", default="") + "")
if os.path.exists(f"{p}/../../../../../packman-repo/packman-common/7.29"):
    sys.path.append(f"{p}/../../../../../packman-repo/packman-common/7.29")
if os.path.exists(f""):
    sys.path.append(f"")
if os.path.exists(f"{p}/../../pip-packages"):
    sys.path.append(f"{p}/../../pip-packages")
if os.path.exists(f"{p}/../../../_repo/deps/repo_build"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_build")
if os.path.exists(f"{p}/../../../_repo/deps/repo_build_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_build_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_kit_template"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_kit_template")
if os.path.exists(f"{p}/../../../_repo/deps/repo_kit_template_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_kit_template_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_kit_tools"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_kit_tools")
if os.path.exists(f"{p}/../../../_repo/deps/repo_kit_tools_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_kit_tools_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_man"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_man")
if os.path.exists(f"{p}/../../../_repo/deps/repo_man_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_man_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_package"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_package")
if os.path.exists(f"{p}/../../../_repo/deps/repo_test"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_test")
if os.path.exists(f"{p}/../../../_repo/deps/repo_test_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_test_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_update_deps"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_update_deps")
if os.path.exists(f"{p}/../../../_repo/deps/repo_usd"):
    sys.path.append(f"{p}/../../../_repo/deps/repo_usd")
if os.path.exists(f"{p}/../../../tools/repoman"):
    sys.path.append(f"{p}/../../../tools/repoman")
if os.path.exists(f"{p}/exts/omni.performance.monitor"):
    sys.path.append(f"{p}/exts/omni.performance.monitor")
if os.path.exists(f"{p}/exts/omni.webcam.viewport"):
    sys.path.append(f"{p}/exts/omni.webcam.viewport")
if os.path.exists(f"{p}/extscache/carb.audio-0.1.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/carb.audio-0.1.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/carb.windowing.plugins-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/carb.windowing.plugins-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.activity.core-1.0.3+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.activity.core-1.0.3+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.activity.profiler-1.0.4+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.activity.profiler-1.0.4+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.activity.pump-1.0.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.activity.pump-1.0.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.anim.curve.core-1.4.2+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.anim.curve.core-1.4.2+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.appwindow-1.2.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.appwindow-1.2.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.assets.plugins-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.assets.plugins-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.blobkey-1.1.2+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.blobkey-1.1.2+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.client-1.3.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.client-1.3.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.convexdecomposition-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.convexdecomposition-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.cubric-0.1.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.cubric-0.1.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.datastore-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.datastore-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.fabric.commands-1.1.6+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.fabric.commands-1.1.6+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.gpucompute.plugins-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.gpucompute.plugins-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.gpu_foundation-0.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.gpu_foundation-0.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.gpu_foundation.shadercache.d3d12-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.gpu_foundation.shadercache.d3d12-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.graph-1.141.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.graph-1.141.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.graph.action-1.140.0+108.0.0"):
    sys.path.append(f"{p}/extscache/omni.graph.action-1.140.0+108.0.0")
if os.path.exists(f"{p}/extscache/omni.graph.action_core-1.1.7+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.graph.action_core-1.1.7+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.graph.action_nodes-1.61.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.graph.action_nodes-1.61.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.graph.action_nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.graph.action_nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.graph.core-2.184.7+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.graph.core-2.184.7+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.graph.exec-0.9.6+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.graph.exec-0.9.6+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.graph.image.core-0.6.1+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.graph.image.core-0.6.1+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.graph.image.nodes-1.3.1+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.graph.image.nodes-1.3.1+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.graph.nodes-1.180.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.graph.nodes-1.180.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.graph.nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.graph.nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.graph.scriptnode-1.60.0+108.0.0"):
    sys.path.append(f"{p}/extscache/omni.graph.scriptnode-1.60.0+108.0.0")
if os.path.exists(f"{p}/extscache/omni.graph.tools-1.79.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.graph.tools-1.79.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.graph.ui_nodes-1.60.2+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.graph.ui_nodes-1.60.2+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.grpc.lib-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.grpc.lib-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.hsscclient-1.1.3+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.hsscclient-1.1.3+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.hydra.engine.stats-1.0.3+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.hydra.engine.stats-1.0.3+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.hydra.rtx-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.hydra.rtx-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.hydra.rtx.shadercache.d3d12-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.hydra.rtx.shadercache.d3d12-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.hydra.scene_api-0.1.3+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.hydra.scene_api-0.1.3+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.hydra.scene_delegate-0.3.4+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.hydra.scene_delegate-0.3.4+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.hydra.usdrt_delegate-7.5.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.hydra.usdrt_delegate-7.5.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.index-1.0.1+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.index-1.0.1+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.index.libs-387500.939.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.index.libs-387500.939.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.iray.libs-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.iray.libs-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.kit.actions.core-1.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.actions.core-1.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.asset_converter-5.0.12+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.kit.asset_converter-5.0.12+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.kit.audiodeviceenum-1.0.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.audiodeviceenum-1.0.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.clipboard-1.1.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.clipboard-1.1.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.commands-1.4.10+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.commands-1.4.10+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.context_menu-1.8.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.context_menu-1.8.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.debug.python-1.0.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.python-1.0.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.debug.settings-1.0.2"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.settings-1.0.2")
if os.path.exists(f"{p}/extscache/omni.kit.debug.vscode-0.1.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.vscode-0.1.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.dev.utilities.bundle-0.2.1"):
    sys.path.append(f"{p}/extscache/omni.kit.dev.utilities.bundle-0.2.1")
if os.path.exists(f"{p}/extscache/omni.kit.developer.bundle-0.2.0"):
    sys.path.append(f"{p}/extscache/omni.kit.developer.bundle-0.2.0")
if os.path.exists(f"{p}/extscache/omni.kit.exec.core-0.13.4+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.exec.core-0.13.4+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.helper.file_utils-0.1.9+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.helper.file_utils-0.1.9+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.hotkeys.core-1.3.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.hotkeys.core-1.3.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.hydra_texture-1.4.7+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.hydra_texture-1.4.7+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.loop-default-0.2.2+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.kit.loop-default-0.2.2+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.kit.mainwindow-1.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.mainwindow-1.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.camera-106.0.5+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.camera-106.0.5+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim-107.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim-107.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.core-107.0.8+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.core-107.0.8+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.fabric-107.0.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.fabric-107.0.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.usd-107.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.usd-107.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.selection-106.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.selection-106.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.selector-1.1.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.selector-1.1.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.tool.snap-1.5.13+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.tool.snap-1.5.13+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.transform-107.0.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.transform-107.0.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.material.library-2.0.9+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.material.library-2.0.9+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.common-2.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.common-2.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.core-1.1.2+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.core-1.1.2+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.create-2.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.create-2.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.edit-2.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.edit-2.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.file-1.1.21+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.file-1.1.21+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.menu.utils-2.1.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.utils-2.1.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.notification_manager-1.0.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.notification_manager-1.0.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.pipapi-0.0.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.pipapi-0.0.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.pip_archive-0.0.0+5941509b.wx64.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.pip_archive-0.0.0+5941509b.wx64.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.primitive.mesh-1.0.17+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.primitive.mesh-1.0.17+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.core-1.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.core-1.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.fabric-1.0.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.fabric-1.0.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.usd-1.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.usd-1.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.audio-1.0.16+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.audio-1.0.16+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.bundle-1.4.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.bundle-1.4.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.camera-1.0.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.camera-1.0.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.geometry-2.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.geometry-2.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.light-1.0.13+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.light-1.0.13+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.material-1.12.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.material-1.12.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.render-1.2.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.render-1.2.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.transform-1.6.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.transform-1.6.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.property.usd-4.6.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.property.usd-4.6.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.raycast.query-1.1.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.raycast.query-1.1.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.capture-1.0.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.capture-1.0.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.core-1.1.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.core-1.1.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.imgui-2.0.6+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.imgui-2.0.6+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.init-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.init-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.kit.selection-0.1.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.selection-0.1.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.stage_template.core-1.1.22+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.stage_template.core-1.1.22+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.telemetry-0.5.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.telemetry-0.5.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.test-2.0.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.test-2.0.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.tool.asset_importer-5.0.4+108.0.0"):
    sys.path.append(f"{p}/extscache/omni.kit.tool.asset_importer-5.0.4+108.0.0")
if os.path.exists(f"{p}/extscache/omni.kit.tool.collect-2.2.18+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.tool.collect-2.2.18+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.ui.actions-1.0.5+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.ui.actions-1.0.5+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.usd.collect-2.4.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.collect-2.4.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.usd.layers-2.3.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.layers-2.3.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.usd.mdl-1.1.5+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.mdl-1.1.5+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.usdz_export-1.0.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.usdz_export-1.0.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.usd_undo-0.1.8+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.usd_undo-0.1.8+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.actions-107.0.2+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.actions-107.0.2+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.legacy_gizmos-1.0.21+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.legacy_gizmos-1.0.21+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.manipulator.transform-107.0.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.manipulator.transform-107.0.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.camera-107.0.7+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.camera-107.0.7+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.core-107.2.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.core-107.2.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.display-107.1.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.display-107.1.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.lighting-107.3.1+107.3.0"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.lighting-107.3.1+107.3.0")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.render-107.0.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.render-107.0.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.settings-107.0.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.settings-107.0.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.ready-1.0.9+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.ready-1.0.9+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.registry-104.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.registry-104.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.scene_camera_model-1.0.6+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.scene_camera_model-1.0.6+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.utility-1.2.2+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.utility-1.2.2+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.window-107.0.14+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.window-107.0.14+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.browser_bar-2.0.10+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.browser_bar-2.0.10+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.context_menu-1.2.5+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.context_menu-1.2.5+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.filebrowser-2.12.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.filebrowser-2.12.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.filter-1.1.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.filter-1.1.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.highlight_label-1.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.highlight_label-1.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.nucleus_connector-2.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.nucleus_connector-2.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.options_button-1.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.options_button-1.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.options_menu-1.1.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.options_menu-1.1.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.path_field-2.0.12+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.path_field-2.0.12+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.prompt-1.0.7+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.prompt-1.0.7+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.searchable_combobox-1.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.searchable_combobox-1.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.searchfield-1.1.8+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.searchfield-1.1.8+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.settings-1.2.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.settings-1.2.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.stage-3.1.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.stage-3.1.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.stage_icons-1.0.8+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.stage_icons-1.0.8+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.text_editor-1.1.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.text_editor-1.1.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.widget.toolbar-2.0.2+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.toolbar-2.0.2+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.widget.viewport-108.0.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.viewport-108.0.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.commands-0.2.9+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.commands-0.2.9+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.console-1.1.4+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.window.console-1.1.4+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.window.content_browser-3.1.4+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.content_browser-3.1.4+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.content_browser_registry-0.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.content_browser_registry-0.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.drop_support-1.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.drop_support-1.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.extensions-1.5.2+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.extensions-1.5.2+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.file-2.0.7+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file-2.0.7+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.filepicker-2.13.7+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.filepicker-2.13.7+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.file_exporter-1.0.35+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file_exporter-1.0.35+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.file_importer-1.1.18+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file_importer-1.1.18+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.popup_dialog-2.0.24+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.popup_dialog-2.0.24+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.preferences-1.8.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.preferences-1.8.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.property-1.14.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.property-1.14.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.script_editor-2.0.3+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.script_editor-2.0.3+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.stage-2.6.1+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.stage-2.6.1+5941509b")
if os.path.exists(f"{p}/extscache/omni.kit.window.status_bar-0.1.9+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.kit.window.status_bar-0.1.9+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.kit.window.toolbar-2.0.0+5941509b"):
    sys.path.append(f"{p}/extscache/omni.kit.window.toolbar-2.0.0+5941509b")
if os.path.exists(f"{p}/extscache/omni.kvdb-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.kvdb-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.localcache-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.localcache-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.materialx.libs-1.0.9+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.materialx.libs-1.0.9+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.mdl-56.0.3+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.mdl-56.0.3+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.mdl.neuraylib-0.2.15+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.mdl.neuraylib-0.2.15+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.metrics.core-0.0.3+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.metrics.core-0.0.3+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.ocio-0.1.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.ocio-0.1.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.physics-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physics-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.physics.physx-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physics.physx-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.physics.stageupdate-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physics.stageupdate-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.physx-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physx-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.physx.cooking-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physx.cooking-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.physx.foundation-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.physx.foundation-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.protobuf.lib-1.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.protobuf.lib-1.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.rtx.settings.core-0.6.5+5941509b"):
    sys.path.append(f"{p}/extscache/omni.rtx.settings.core-0.6.5+5941509b")
if os.path.exists(f"{p}/extscache/omni.rtx.window.settings-0.6.101+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.rtx.window.settings-0.6.101+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.stats-1.0.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.stats-1.0.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.timeline-1.1.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.timeline-1.1.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.ui-2.27.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.ui-2.27.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.ui.scene-1.11.4+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.ui.scene-1.11.4+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.uiaudio-1.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.uiaudio-1.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.ujitso.client-0.0.0+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.ujitso.client-0.0.0+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.ujitso.default-1.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.ujitso.default-1.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd-1.13.13+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd-1.13.13+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.config-1.0.6+5941509b"):
    sys.path.append(f"{p}/extscache/omni.usd.config-1.0.6+5941509b")
if os.path.exists(f"{p}/extscache/omni.usd.core-1.5.4+5941509b.wx64.r"):
    sys.path.append(f"{p}/extscache/omni.usd.core-1.5.4+5941509b.wx64.r")
if os.path.exists(f"{p}/extscache/omni.usd.libs-1.0.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd.libs-1.0.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.usd.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.usd.metrics.assembler.ui-108.0.0+108.0.0.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.usd.metrics.assembler.ui-108.0.0+108.0.0.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.usd.schema.anim-0.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.anim-0.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.schema.audio-0.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.audio-0.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.schema.geospatial-0.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.geospatial-0.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.schema.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.usd.schema.omnigraph-1.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.omnigraph-1.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.usd.schema.physx-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.physx-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.usdphysics-108.0.4+108.0.0.wx64.r.cp312.u81f"):
    sys.path.append(f"{p}/extscache/omni.usdphysics-108.0.4+108.0.0.wx64.r.cp312.u81f")
if os.path.exists(f"{p}/extscache/omni.usd_resolver-1.0.0+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.usd_resolver-1.0.0+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.volume-0.5.2+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/omni.volume-0.5.2+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/omni.warp.core-1.8.1+wx64"):
    sys.path.append(f"{p}/extscache/omni.warp.core-1.8.1+wx64")
if os.path.exists(f"{p}/extscache/usdrt.scenegraph-7.6.1+5941509b.wx64.r.cp312"):
    sys.path.append(f"{p}/extscache/usdrt.scenegraph-7.6.1+5941509b.wx64.r.cp312")
if os.path.exists(f"{p}/extscache/carb.audio-0.1.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/carb.audio-0.1.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/carb.windowing.plugins-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/carb.windowing.plugins-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.activity.core-1.0.3+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.activity.core-1.0.3+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.activity.profiler-1.0.4+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.activity.profiler-1.0.4+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.activity.pump-1.0.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.activity.pump-1.0.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.anim.curve.core-1.4.2+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.anim.curve.core-1.4.2+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.appwindow-1.2.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.appwindow-1.2.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.assets.plugins-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.assets.plugins-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.blobkey-1.1.2+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.blobkey-1.1.2+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.client-1.3.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.client-1.3.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.convexdecomposition-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.convexdecomposition-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.cubric-0.1.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.cubric-0.1.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.datastore-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.datastore-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.fabric.commands-1.1.6+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.fabric.commands-1.1.6+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.gpucompute.plugins-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.gpucompute.plugins-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.gpu_foundation-0.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.gpu_foundation-0.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.gpu_foundation.shadercache.d3d12-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.gpu_foundation.shadercache.d3d12-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph-1.141.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph-1.141.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.action-1.140.0+108.0.0/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.action-1.140.0+108.0.0/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.action_core-1.1.7+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.action_core-1.1.7+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.action_nodes-1.61.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.action_nodes-1.61.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.action_nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.action_nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.core-2.184.7+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.core-2.184.7+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.exec-0.9.6+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.exec-0.9.6+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.image.core-0.6.1+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.image.core-0.6.1+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.image.nodes-1.3.1+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.image.nodes-1.3.1+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.nodes-1.180.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.nodes-1.180.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.nodes_core-1.10.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.scriptnode-1.60.0+108.0.0/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.scriptnode-1.60.0+108.0.0/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.tools-1.79.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.tools-1.79.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.graph.ui_nodes-1.60.2+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.graph.ui_nodes-1.60.2+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.grpc.lib-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.grpc.lib-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hsscclient-1.1.3+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hsscclient-1.1.3+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.engine.stats-1.0.3+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.engine.stats-1.0.3+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.rtx-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.rtx-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.rtx.shadercache.d3d12-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.rtx.shadercache.d3d12-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.scene_api-0.1.3+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.scene_api-0.1.3+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.scene_delegate-0.3.4+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.scene_delegate-0.3.4+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.hydra.usdrt_delegate-7.5.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.hydra.usdrt_delegate-7.5.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.index-1.0.1+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.index-1.0.1+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.index.libs-387500.939.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.index.libs-387500.939.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.iray.libs-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.iray.libs-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.actions.core-1.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.actions.core-1.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.asset_converter-5.0.12+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.asset_converter-5.0.12+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.audiodeviceenum-1.0.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.audiodeviceenum-1.0.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.clipboard-1.1.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.clipboard-1.1.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.commands-1.4.10+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.commands-1.4.10+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.context_menu-1.8.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.context_menu-1.8.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.debug.python-1.0.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.python-1.0.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.debug.settings-1.0.2/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.settings-1.0.2/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.debug.vscode-0.1.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.debug.vscode-0.1.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.dev.utilities.bundle-0.2.1/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.dev.utilities.bundle-0.2.1/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.developer.bundle-0.2.0/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.developer.bundle-0.2.0/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.exec.core-0.13.4+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.exec.core-0.13.4+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.helper.file_utils-0.1.9+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.helper.file_utils-0.1.9+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.hotkeys.core-1.3.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.hotkeys.core-1.3.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.hydra_texture-1.4.7+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.hydra_texture-1.4.7+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.loop-default-0.2.2+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.loop-default-0.2.2+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.mainwindow-1.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.mainwindow-1.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.camera-106.0.5+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.camera-106.0.5+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim-107.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim-107.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.core-107.0.8+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.core-107.0.8+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.fabric-107.0.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.fabric-107.0.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.prim.usd-107.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.prim.usd-107.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.selection-106.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.selection-106.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.selector-1.1.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.selector-1.1.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.tool.snap-1.5.13+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.tool.snap-1.5.13+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.manipulator.transform-107.0.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.manipulator.transform-107.0.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.material.library-2.0.9+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.material.library-2.0.9+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.common-2.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.common-2.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.core-1.1.2+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.core-1.1.2+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.create-2.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.create-2.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.edit-2.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.edit-2.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.file-1.1.21+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.file-1.1.21+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.menu.utils-2.1.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.menu.utils-2.1.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.notification_manager-1.0.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.notification_manager-1.0.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.pipapi-0.0.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.pipapi-0.0.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.pip_archive-0.0.0+5941509b.wx64.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.pip_archive-0.0.0+5941509b.wx64.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.primitive.mesh-1.0.17+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.primitive.mesh-1.0.17+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.core-1.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.core-1.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.fabric-1.0.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.fabric-1.0.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.adapter.usd-1.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.adapter.usd-1.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.audio-1.0.16+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.audio-1.0.16+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.bundle-1.4.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.bundle-1.4.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.camera-1.0.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.camera-1.0.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.geometry-2.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.geometry-2.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.light-1.0.13+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.light-1.0.13+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.material-1.12.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.material-1.12.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.render-1.2.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.render-1.2.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.transform-1.6.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.transform-1.6.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.property.usd-4.6.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.property.usd-4.6.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.raycast.query-1.1.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.raycast.query-1.1.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.capture-1.0.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.capture-1.0.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.core-1.1.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.core-1.1.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.imgui-2.0.6+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.imgui-2.0.6+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.renderer.init-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.renderer.init-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.selection-0.1.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.selection-0.1.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.stage_template.core-1.1.22+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.stage_template.core-1.1.22+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.telemetry-0.5.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.telemetry-0.5.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.test-2.0.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.test-2.0.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.tool.asset_importer-5.0.4+108.0.0/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.tool.asset_importer-5.0.4+108.0.0/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.tool.collect-2.2.18+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.tool.collect-2.2.18+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.ui.actions-1.0.5+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.ui.actions-1.0.5+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.usd.collect-2.4.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.collect-2.4.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.usd.layers-2.3.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.layers-2.3.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.usd.mdl-1.1.5+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.usd.mdl-1.1.5+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.usdz_export-1.0.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.usdz_export-1.0.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.usd_undo-0.1.8+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.usd_undo-0.1.8+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.actions-107.0.2+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.actions-107.0.2+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.legacy_gizmos-1.0.21+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.legacy_gizmos-1.0.21+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.manipulator.transform-107.0.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.manipulator.transform-107.0.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.camera-107.0.7+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.camera-107.0.7+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.core-107.2.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.core-107.2.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.display-107.1.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.display-107.1.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.lighting-107.3.1+107.3.0/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.lighting-107.3.1+107.3.0/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.render-107.0.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.render-107.0.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.menubar.settings-107.0.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.menubar.settings-107.0.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.ready-1.0.9+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.ready-1.0.9+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.registry-104.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.registry-104.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.scene_camera_model-1.0.6+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.scene_camera_model-1.0.6+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.utility-1.2.2+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.utility-1.2.2+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.viewport.window-107.0.14+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.viewport.window-107.0.14+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.browser_bar-2.0.10+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.browser_bar-2.0.10+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.context_menu-1.2.5+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.context_menu-1.2.5+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.filebrowser-2.12.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.filebrowser-2.12.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.filter-1.1.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.filter-1.1.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.highlight_label-1.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.highlight_label-1.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.nucleus_connector-2.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.nucleus_connector-2.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.options_button-1.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.options_button-1.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.options_menu-1.1.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.options_menu-1.1.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.path_field-2.0.12+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.path_field-2.0.12+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.prompt-1.0.7+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.prompt-1.0.7+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.searchable_combobox-1.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.searchable_combobox-1.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.searchfield-1.1.8+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.searchfield-1.1.8+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.settings-1.2.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.settings-1.2.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.stage-3.1.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.stage-3.1.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.stage_icons-1.0.8+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.stage_icons-1.0.8+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.text_editor-1.1.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.text_editor-1.1.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.toolbar-2.0.2+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.toolbar-2.0.2+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.widget.viewport-108.0.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.widget.viewport-108.0.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.commands-0.2.9+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.commands-0.2.9+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.console-1.1.4+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.console-1.1.4+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.content_browser-3.1.4+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.content_browser-3.1.4+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.content_browser_registry-0.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.content_browser_registry-0.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.drop_support-1.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.drop_support-1.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.extensions-1.5.2+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.extensions-1.5.2+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.file-2.0.7+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file-2.0.7+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.filepicker-2.13.7+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.filepicker-2.13.7+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.file_exporter-1.0.35+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file_exporter-1.0.35+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.file_importer-1.1.18+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.file_importer-1.1.18+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.popup_dialog-2.0.24+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.popup_dialog-2.0.24+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.preferences-1.8.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.preferences-1.8.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.property-1.14.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.property-1.14.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.script_editor-2.0.3+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.script_editor-2.0.3+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.stage-2.6.1+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.stage-2.6.1+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.status_bar-0.1.9+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.status_bar-0.1.9+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kit.window.toolbar-2.0.0+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kit.window.toolbar-2.0.0+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.kvdb-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.kvdb-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.localcache-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.localcache-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.materialx.libs-1.0.9+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.materialx.libs-1.0.9+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.mdl-56.0.3+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.mdl-56.0.3+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.mdl.neuraylib-0.2.15+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.mdl.neuraylib-0.2.15+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.metrics.core-0.0.3+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.metrics.core-0.0.3+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.ocio-0.1.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.ocio-0.1.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physics-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physics-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physics.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physics.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physics.stageupdate-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physics.stageupdate-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physx.cooking-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physx.cooking-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.physx.foundation-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.physx.foundation-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.protobuf.lib-1.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.protobuf.lib-1.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.rtx.settings.core-0.6.5+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.rtx.settings.core-0.6.5+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.rtx.window.settings-0.6.101+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.rtx.window.settings-0.6.101+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.stats-1.0.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.stats-1.0.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.timeline-1.1.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.timeline-1.1.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.ui-2.27.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.ui-2.27.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.ui.scene-1.11.4+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.ui.scene-1.11.4+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.uiaudio-1.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.uiaudio-1.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.ujitso.client-0.0.0+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.ujitso.client-0.0.0+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.ujitso.default-1.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.ujitso.default-1.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd-1.13.13+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd-1.13.13+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.config-1.0.6+5941509b/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.config-1.0.6+5941509b/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.core-1.5.4+5941509b.wx64.r/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.core-1.5.4+5941509b.wx64.r/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.libs-1.0.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.libs-1.0.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.metrics.assembler.ui-108.0.0+108.0.0.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.metrics.assembler.ui-108.0.0+108.0.0.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.anim-0.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.anim-0.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.audio-0.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.audio-0.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.geospatial-0.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.geospatial-0.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.metrics.assembler-108.0.0+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.omnigraph-1.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.omnigraph-1.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd.schema.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd.schema.physx-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usdphysics-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usdphysics-108.0.4+108.0.0.wx64.r.cp312.u81f/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.usd_resolver-1.0.0+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.usd_resolver-1.0.0+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.volume-0.5.2+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.volume-0.5.2+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/extscache/omni.warp.core-1.8.1+wx64/pip_prebundle"):
    sys.path.append(f"{p}/extscache/omni.warp.core-1.8.1+wx64/pip_prebundle")
if os.path.exists(f"{p}/extscache/usdrt.scenegraph-7.6.1+5941509b.wx64.r.cp312/pip_prebundle"):
    sys.path.append(f"{p}/extscache/usdrt.scenegraph-7.6.1+5941509b.wx64.r.cp312/pip_prebundle")
if os.path.exists(f"{p}/kit/extscore/omni.client.lib"):
    sys.path.append(f"{p}/kit/extscore/omni.client.lib")
if os.path.exists(f"{p}/kit/extscore/omni.kit.async_engine"):
    sys.path.append(f"{p}/kit/extscore/omni.kit.async_engine")
if os.path.exists(f"{p}/kit/extscore/omni.kit.registry.nucleus"):
    sys.path.append(f"{p}/kit/extscore/omni.kit.registry.nucleus")
if os.path.exists(f"{p}/kit/kernel/py"):
    sys.path.append(f"{p}/kit/kernel/py")
if os.path.exists(f"" + os.getenv("PATH", default="") + ""):
    add_library_path(f"" + os.getenv("PATH", default="") + "")
if os.path.exists(f"{p}/."):
    add_library_path(f"{p}/.")
